(tests
 (names test_solver test_git test_highlight test_cursor test_tree test_scrollbar
   test_clipboard test_stack test_terminal test_session)
 (libraries async bonsai_term core gitter grammar_registry tree-sitter)
 (link_flags (-cclib -Wl,-w)) ; silence SDK-version ld warning flood
 (preprocess
  (pps ppx_jane)))
