(* GENERATED by scripts/add-grammar — the query lives in highlights.scm. *)
external language_ptr : unit -> nativeint = "caml_gitter_grammar_rust_language"

let language () = Tree_sitter.Language.of_address (language_ptr ())
let highlights_query = Query_source.source
