(* GENERATED by scripts/add-grammar — do not edit. *)
let find = function
  | "c" -> Some Gitter_grammar_c.highlight
  | "h" -> Some Gitter_grammar_c.highlight
  | "js" -> Some Gitter_grammar_javascript.highlight
  | "mjs" -> Some Gitter_grammar_javascript.highlight
  | "cjs" -> Some Gitter_grammar_javascript.highlight
  | "jsx" -> Some Gitter_grammar_javascript.highlight
  | "py" -> Some Gitter_grammar_python.highlight
  | _ -> None

let extensions =
  [
    "c";
    "h";
    "js";
    "mjs";
    "cjs";
    "jsx";
    "py";
  ]
