(* GENERATED by scripts/add-grammar — do not edit. *)
type spec =
  { language : unit -> Tree_sitter.Language.t
  ; highlights_query : string
  }

let find = function
  | "c" -> Some { language = Gitter_grammar_c.language; highlights_query = Gitter_grammar_c.highlights_query }
  | "h" -> Some { language = Gitter_grammar_c.language; highlights_query = Gitter_grammar_c.highlights_query }
  | "cpp" -> Some { language = Gitter_grammar_cpp.language; highlights_query = Gitter_grammar_cpp.highlights_query }
  | "cc" -> Some { language = Gitter_grammar_cpp.language; highlights_query = Gitter_grammar_cpp.highlights_query }
  | "cxx" -> Some { language = Gitter_grammar_cpp.language; highlights_query = Gitter_grammar_cpp.highlights_query }
  | "hpp" -> Some { language = Gitter_grammar_cpp.language; highlights_query = Gitter_grammar_cpp.highlights_query }
  | "hh" -> Some { language = Gitter_grammar_cpp.language; highlights_query = Gitter_grammar_cpp.highlights_query }
  | "js" -> Some { language = Gitter_grammar_javascript.language; highlights_query = Gitter_grammar_javascript.highlights_query }
  | "mjs" -> Some { language = Gitter_grammar_javascript.language; highlights_query = Gitter_grammar_javascript.highlights_query }
  | "cjs" -> Some { language = Gitter_grammar_javascript.language; highlights_query = Gitter_grammar_javascript.highlights_query }
  | "jsx" -> Some { language = Gitter_grammar_javascript.language; highlights_query = Gitter_grammar_javascript.highlights_query }
  | "py" -> Some { language = Gitter_grammar_python.language; highlights_query = Gitter_grammar_python.highlights_query }
  | _ -> None

let extensions =
  [
    "c";
    "h";
    "cpp";
    "cc";
    "cxx";
    "hpp";
    "hh";
    "js";
    "mjs";
    "cjs";
    "jsx";
    "py";
  ]
